services:
  minio:
    image: minio/minio:latest
    container_name: tvdb-minio
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: tvdb-images
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - tvdb-network

volumes:
  minio_data:
    driver: local

networks:
  tvdb-network:
    external: true
    name: tvdb-local_default